// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD67NAh86i3yQ0FSWzGNCPAAAKAla9Eh-o',
    appId: '1:571999879235:web:c489df872658264ad394f6',
    messagingSenderId: '571999879235',
    projectId: 'doanmobile-6c221',
    authDomain: 'doanmobile-6c221.firebaseapp.com',
    storageBucket: 'doanmobile-6c221.firebasestorage.app',
    measurementId: 'G-P4H0PZ0JZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkOG2jRSmjM4VXH8JNk8FlT1F8nsMf4g8',
    appId: '1:571999879235:android:5b156255c723dceed394f6',
    messagingSenderId: '571999879235',
    projectId: 'doanmobile-6c221',
    storageBucket: 'doanmobile-6c221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgI9dzgz3nVtJEIoUWvGA80BsJ5GMtzaU',
    appId: '1:571999879235:ios:095ec37610d134d9d394f6',
    messagingSenderId: '571999879235',
    projectId: 'doanmobile-6c221',
    storageBucket: 'doanmobile-6c221.firebasestorage.app',
    iosBundleId: 'com.example.nguyenanhkhoi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgI9dzgz3nVtJEIoUWvGA80BsJ5GMtzaU',
    appId: '1:571999879235:ios:095ec37610d134d9d394f6',
    messagingSenderId: '571999879235',
    projectId: 'doanmobile-6c221',
    storageBucket: 'doanmobile-6c221.firebasestorage.app',
    iosBundleId: 'com.example.nguyenanhkhoi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD67NAh86i3yQ0FSWzGNCPAAAKAla9Eh-o',
    appId: '1:571999879235:web:f653566ab25f2dbad394f6',
    messagingSenderId: '571999879235',
    projectId: 'doanmobile-6c221',
    authDomain: 'doanmobile-6c221.firebaseapp.com',
    storageBucket: 'doanmobile-6c221.firebasestorage.app',
    measurementId: 'G-JRB6X5WR0N',
  );

}